// ============================================
// Job Data - 60 Realistic Indian Tech Jobs
// ============================================

const jobsData = [
    // Internships & Fresher roles
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "DSA", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
        description: "Join Amazon as an SDE Intern and work on real-world problems. You'll collaborate with experienced engineers on scalable systems. Strong foundation in data structures and algorithms required. 6-month internship with potential for full-time conversion."
    },
    {
        id: 2,
        title: "Frontend Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "HTML/CSS"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://razorpay.com/jobs/frontend-intern",
        description: "Build beautiful payment interfaces used by millions. Work with React and modern frontend tools. Learn from senior engineers in a fast-paced fintech environment. 3-6 month internship program."
    },
    {
        id: 3,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "3.5–4 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Join Infosys GET program with comprehensive training. Work on enterprise projects for global clients. Training includes Java, databases, and soft skills. Excellent career growth opportunities in IT services."
    },
    {
        id: 4,
        title: "QA Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "API Testing"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://flipkart.com/careers/qa-intern",
        description: "Ensure quality of India's largest e-commerce platform. Learn automated testing, API testing, and quality processes. Work with product and engineering teams. 6-month internship."
    },
    {
        id: 5,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel", "Data Visualization"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹22k–₹35k/month Internship",
        applyUrl: "https://swiggy.com/careers/data-analyst-intern",
        description: "Analyze food delivery data to drive business decisions. Work with large datasets using SQL and Python. Create dashboards and reports for stakeholders. Learn from experienced data scientists."
    },

    // 0-1 Year Experience
    {
        id: 6,
        title: "Java Developer (0-1 Year)",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "https://tcs.com/careers/java-developer",
        description: "Develop enterprise Java applications for banking clients. Work with Spring Boot and microservices architecture. Collaborate with global teams. Training provided for freshers with basic Java knowledge."
    },
    {
        id: 7,
        title: "Python Developer (Fresher)",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "Django", "REST APIs"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "3.5–5.5 LPA",
        applyUrl: "https://wipro.com/careers/python-dev",
        description: "Build backend services using Python and Django. Work on cloud-native applications. Exposure to AWS and containerization. Great learning environment for Python enthusiasts."
    },
    {
        id: 8,
        title: "Frontend Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["JavaScript", "React", "CSS"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–6 LPA",
        applyUrl: "https://zoho.com/careers/frontend",
        description: "Create user interfaces for Zoho's suite of products. Work with React and modern JavaScript. Product-based company with excellent work culture. Opportunity to impact millions of users."
    },
    {
        id: 9,
        title: "Backend Developer (Node.js)",
        company: "CRED",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Node.js", "MongoDB", "Express"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "https://cred.club/careers/backend-nodejs",
        description: "Build scalable backend systems for India's most trusted credit card platform. Work with Node.js and MongoDB. Fast-paced fintech startup environment. Competitive compensation and ESOPs."
    },
    {
        id: 10,
        title: "Full Stack Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "0-1",
        skills: ["React", "Node.js", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "5–8 LPA",
        applyUrl: "https://freshworks.com/careers/fullstack",
        description: "Work on SaaS products used by Fortune 500 companies. Full stack role with React and Node.js. Remote-first culture with flexible hours. Great benefits and learning opportunities."
    },

    // 1-3 Years Experience
    {
        id: 11,
        title: "React Developer (1-3 Years)",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript", "Jest"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://phonepe.com/careers/react-dev",
        description: "Build India's leading digital payments app used by 400M+ users. Work with React, TypeScript, and modern frontend tools. High-impact role with excellent compensation. Solve complex UI challenges at scale."
    },
    {
        id: 12,
        title: "Backend Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Kafka", "Redis"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "12–20 LPA",
        applyUrl: "https://paytm.com/careers/backend-engineer",
        description: "Design and develop microservices for payment processing. Work with high-throughput distributed systems. Experience with Kafka and Redis preferred. Fintech domain expertise valued."
    },
    {
        id: 13,
        title: "DevOps Engineer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        applyUrl: "https://juspay.in/careers/devops",
        description: "Manage cloud infrastructure for payment gateway processing billions of transactions. Work with AWS, Kubernetes, and modern DevOps tools. Automate deployment pipelines. High-growth fintech company."
    },
    {
        id: 14,
        title: "Mobile Developer (Android)",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://flipkart.com/careers/android-dev",
        description: "Build features for Flipkart's Android app used by millions daily. Work with Kotlin and modern Android architecture. Solve performance and scalability challenges. Great team and learning culture."
    },
    {
        id: 15,
        title: "Data Engineer",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "Spark", "AWS", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15–22 LPA",
        applyUrl: "https://amazon.jobs/en/jobs/data-engineer",
        description: "Build data pipelines processing petabytes of data. Work with Spark, AWS EMR, and Redshift. Enable data-driven decision making across Amazon. Challenging problems at massive scale."
    },

    // More diverse roles
    {
        id: 16,
        title: "Software Engineer",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Angular", "Spring", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://accenture.com/careers/software-engineer",
        description: "Work on digital transformation projects for Fortune 500 clients. Full stack development with Java and Angular. Exposure to multiple domains and technologies. Global opportunities available."
    },
    {
        id: 17,
        title: "QA Automation Engineer",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Selenium", "Java", "TestNG", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "5–9 LPA",
        applyUrl: "https://capgemini.com/careers/qa-automation",
        description: "Automate testing for enterprise applications. Work with Selenium, API testing tools, and CI/CD pipelines. Ensure quality for global clients. Continuous learning and certification support."
    },
    {
        id: 18,
        title: "Cloud Engineer",
        company: "IBM",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["AWS", "Azure", "Terraform", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–14 LPA",
        applyUrl: "https://ibm.com/careers/cloud-engineer",
        description: "Design and implement cloud solutions on AWS and Azure. Infrastructure as code with Terraform. Work with enterprise clients on cloud migration. Remote-friendly with flexible hours."
    },
    {
        id: 19,
        title: "Machine Learning Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "ML Algorithms", "SQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        applyUrl: "https://razorpay.com/careers/ml-engineer",
        description: "Build ML models for fraud detection and risk assessment. Work with large-scale financial data. Apply cutting-edge ML techniques to real-world problems. High-impact fintech role."
    },
    {
        id: 20,
        title: "iOS Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "UIKit", "SwiftUI"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        applyUrl: "https://swiggy.com/careers/ios-developer",
        description: "Develop features for Swiggy's iOS app. Work with Swift and modern iOS frameworks. Solve complex UI and performance challenges. Impact millions of food delivery users daily."
    },

    // Additional roles for variety
    {
        id: 21,
        title: "Graduate Trainee Engineer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Problem Solving"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://cognizant.com/careers/gtt",
        description: "Join Cognizant's GenC program with structured training. Work on client projects across various domains. Comprehensive learning path from basics to advanced topics. Global exposure opportunities."
    },
    {
        id: 22,
        title: "Software Developer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Oracle DB", "PL/SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "5–8 LPA",
        applyUrl: "https://oracle.com/careers/software-dev",
        description: "Develop enterprise database solutions and cloud applications. Work with Oracle technologies and Java. Excellent training and certification programs. Stable product-based company."
    },
    {
        id: 23,
        title: "UI/UX Developer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Figma", "JavaScript", "CSS"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "8–14 LPA",
        applyUrl: "https://sap.com/careers/ui-ux-dev",
        description: "Create intuitive interfaces for SAP's enterprise software. Collaborate with designers and backend teams. Work with React and modern design tools. Global product impact."
    },
    {
        id: 24,
        title: "Backend Developer (Python)",
        company: "Dell",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "FastAPI", "PostgreSQL", "Docker"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "7–12 LPA",
        applyUrl: "https://dell.com/careers/backend-python",
        description: "Build internal tools and APIs using Python. Work on automation and data processing systems. Remote-first role with flexible working hours. Excellent work-life balance."
    },
    {
        id: 25,
        title: "Full Stack Engineer",
        company: "Tekion",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "AWS", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–18 LPA",
        applyUrl: "https://tekion.com/careers/fullstack",
        description: "Build cloud-native automotive retail platform. Work with modern tech stack - React, Node.js, AWS. Fast-growing startup with strong funding. Solve complex domain problems."
    },
    {
        id: 26,
        title: "Data Scientist",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Machine Learning", "Statistics", "SQL"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "14–22 LPA",
        applyUrl: "https://flipkart.com/careers/data-scientist",
        description: "Apply ML and analytics to improve customer experience and business metrics. Work with massive e-commerce datasets. Build recommendation systems and pricing models. High-impact role."
    },
    {
        id: 27,
        title: "SDE-1",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["C++", "DSA", "System Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–25 LPA",
        applyUrl: "https://microsoft.com/careers/sde1",
        description: "Join Microsoft and work on products used by billions. Strong coding and problem-solving skills required. Excellent mentorship and learning culture. Competitive compensation and benefits."
    },
    {
        id: 28,
        title: "Junior Java Developer",
        company: "Mphasis",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring", "Hibernate", "MySQL"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "3–6 LPA",
        applyUrl: "https://mphasis.com/careers/java-dev",
        description: "Develop Java applications for banking and financial services clients. Work with Spring framework and databases. Training provided for freshers. Stable IT services company."
    },
    {
        id: 29,
        title: "React Native Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Redux"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://dunzo.com/careers/react-native",
        description: "Build cross-platform mobile app for hyperlocal delivery. Work with React Native and modern mobile development practices. Fast-paced startup environment. ESOPs included."
    },
    {
        id: 30,
        title: "Backend Engineer (Go)",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Golang", "PostgreSQL", "Redis", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "15–25 LPA",
        applyUrl: "https://zerodha.com/careers/backend-go",
        description: "Build high-performance trading systems using Go. Work on low-latency microservices. India's largest stock broker with bootstrapped growth. Excellent compensation and work culture."
    },

    // More roles to reach 60
    {
        id: 31,
        title: "Software Engineer Trainee",
        company: "HCL Technologies",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "C++", "SQL"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://hcltech.com/careers/trainee",
        description: "Join HCL's training program and work on enterprise projects. Comprehensive technical and soft skills training. Work with global clients across industries. Career growth in IT services."
    },
    {
        id: 32,
        title: "Frontend Engineer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "Webpack", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://meesho.com/careers/frontend",
        description: "Build e-commerce platform for Bharat. Work on performance optimization and user experience. High-growth social commerce startup. Solve unique challenges at scale."
    },
    {
        id: 33,
        title: "QA Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Manual Testing", "Automation", "Appium"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "4–7 LPA",
        applyUrl: "https://ola.com/careers/qa-engineer",
        description: "Ensure quality of India's ride-hailing platform. Test mobile apps and backend services. Learn automation testing with Selenium and Appium. Fast-paced mobility startup."
    },
    {
        id: 34,
        title: "DevOps Intern",
        company: "Hashedin",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "Git", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://hashedin.com/careers/devops-intern",
        description: "Learn DevOps practices in a product engineering company. Work with AWS, Docker, and CI/CD tools. Mentorship from experienced DevOps engineers. 6-month internship with PPO possibility."
    },
    {
        id: 35,
        title: "Data Analyst",
        company: "Myntra",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["SQL", "Python", "Tableau", "Excel"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "5–9 LPA",
        applyUrl: "https://myntra.com/careers/data-analyst",
        description: "Analyze fashion e-commerce data to drive business insights. Create dashboards and reports for stakeholders. Work with product and marketing teams. Learn from data science experts."
    },
    {
        id: 36,
        title: "Java Full Stack Developer",
        company: "LTI Mindtree",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Angular", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "6–11 LPA",
        applyUrl: "https://ltimindtree.com/careers/fullstack-java",
        description: "Develop full stack applications for banking and insurance clients. Work with Java Spring Boot and Angular. Exposure to cloud technologies. Global project opportunities."
    },
    {
        id: 37,
        title: "Python Backend Developer",
        company: "Cure.fit",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Django", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "8–14 LPA",
        applyUrl: "https://curefit.com/careers/python-backend",
        description: "Build health and fitness platform backend. Work with Django and microservices. Impact millions of health-conscious users. Startup culture with good work-life balance."
    },
    {
        id: 38,
        title: "Mobile App Developer",
        company: "Byju's",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Flutter", "Dart", "Firebase"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "5–9 LPA",
        applyUrl: "https://byjus.com/careers/mobile-dev",
        description: "Develop educational apps using Flutter. Work on features used by millions of students. Learn cross-platform mobile development. EdTech domain with social impact."
    },
    {
        id: 39,
        title: "Software Development Engineer",
        company: "Walmart Labs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Microservices", "Kafka", "Cassandra"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        applyUrl: "https://walmartlabs.com/careers/sde",
        description: "Build e-commerce and supply chain systems at global scale. Work with distributed systems and big data. Solve complex technical challenges. Excellent compensation and benefits."
    },
    {
        id: 40,
        title: "Cloud Developer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["AWS", "Python", "Serverless", "Lambda"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "4–7 LPA",
        applyUrl: "https://techmahindra.com/careers/cloud-dev",
        description: "Develop cloud-native applications on AWS. Work with serverless architecture and Lambda functions. Training on cloud technologies provided. Telecom and enterprise clients."
    },
    {
        id: 41,
        title: "Backend Developer",
        company: "Udaan",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "MongoDB", "Redis", "RabbitMQ"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–16 LPA",
        applyUrl: "https://udaan.com/careers/backend-dev",
        description: "Build B2B e-commerce platform for Indian businesses. Work with Node.js and distributed systems. High-impact role in growing startup. Solve unique supply chain problems."
    },
    {
        id: 42,
        title: "Frontend Developer (Vue.js)",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Vue.js", "JavaScript", "TypeScript", "CSS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "15–22 LPA",
        applyUrl: "https://postman.com/careers/frontend-vue",
        description: "Build API development tools used by 20M+ developers worldwide. Work with Vue.js and modern frontend stack. Remote-first company with global team. Excellent compensation and ESOPs."
    },
    {
        id: 43,
        title: "Test Automation Engineer",
        company: "Publicis Sapient",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Java", "Cucumber", "Jenkins"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "7–12 LPA",
        applyUrl: "https://publicissapient.com/careers/test-automation",
        description: "Automate testing for digital transformation projects. Work with Selenium, API testing, and CI/CD. Exposure to multiple industries and clients. Continuous learning culture."
    },
    {
        id: 44,
        title: "AI/ML Intern",
        company: "Navi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Machine Learning", "TensorFlow"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://navi.com/careers/ml-intern",
        description: "Work on ML models for fintech applications. Learn from experienced data scientists. Apply ML to credit scoring and fraud detection. 6-month internship in fast-growing fintech."
    },
    {
        id: 45,
        title: "Java Microservices Developer",
        company: "Nagarro",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Microservices", "Docker"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–14 LPA",
        applyUrl: "https://nagarro.com/careers/java-microservices",
        description: "Build microservices for enterprise clients. Work with Spring Boot, Docker, and Kubernetes. Agile development environment. Global software engineering company."
    },
    {
        id: 46,
        title: "React Developer",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "JavaScript", "Webpack"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "12–20 LPA",
        applyUrl: "https://groww.in/careers/react-developer",
        description: "Build investment platform UI used by millions of Indians. Work with React and modern frontend tools. Fast-growing fintech unicorn. Solve complex financial UI challenges."
    },
    {
        id: 47,
        title: "Backend Engineer (Scala)",
        company: "Gojek",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Scala", "Akka", "Kafka", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "14–22 LPA",
        applyUrl: "https://gojek.com/careers/backend-scala",
        description: "Build super app backend serving millions in Southeast Asia. Work with Scala and functional programming. High-performance distributed systems. International exposure."
    },
    {
        id: 48,
        title: "Site Reliability Engineer",
        company: "Airtel X Labs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Linux", "Python", "Kubernetes", "Monitoring"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        applyUrl: "https://airtel.in/careers/sre",
        description: "Ensure reliability of telecom and digital services. Work with Kubernetes, monitoring tools, and automation. Learn SRE practices at scale. Telecom giant's innovation lab."
    },
    {
        id: 49,
        title: "Full Stack Developer (MEAN)",
        company: "Mindtree",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["MongoDB", "Express", "Angular", "Node.js"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "4–7 LPA",
        applyUrl: "https://mindtree.com/careers/mean-stack",
        description: "Develop full stack applications using MEAN stack. Work on digital transformation projects. Training provided for MEAN technologies. IT services with good work culture."
    },
    {
        id: 50,
        title: "Junior Data Engineer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Python", "SQL", "Airflow", "AWS"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://olaelectric.com/careers/data-engineer",
        description: "Build data pipelines for EV analytics and IoT data. Work with modern data stack - Airflow, Spark, AWS. Electric vehicle revolution in India. Innovative mobility startup."
    },
    {
        id: 51,
        title: "Software Engineer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "JavaScript", "Salesforce", "APIs"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "10–16 LPA",
        applyUrl: "https://salesforce.com/careers/software-engineer",
        description: "Develop CRM solutions on Salesforce platform. Work with enterprise clients globally. Excellent training and certification programs. Top-tier product company with great culture."
    },
    {
        id: 52,
        title: "Android Developer",
        company: "ShareChat",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android", "MVVM", "Jetpack"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://sharechat.com/careers/android",
        description: "Build social media app for Bharat in 15 Indian languages. Work with Kotlin and modern Android architecture. High-growth Indian social media unicorn. Impact 180M+ users."
    },
    {
        id: 53,
        title: "Backend Developer (Ruby)",
        company: "Chargebee",
        location: "Chennai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Ruby on Rails", "PostgreSQL", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "12–18 LPA",
        applyUrl: "https://chargebee.com/careers/backend-ruby",
        description: "Build subscription billing platform used by 4000+ SaaS companies. Work with Ruby on Rails. Remote-first Chennai-based SaaS unicorn. Global product impact."
    },
    {
        id: 54,
        title: "Cybersecurity Analyst",
        company: "Infosys",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Network Security", "Ethical Hacking", "SIEM"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "4–7 LPA",
        applyUrl: "https://infosys.com/careers/cybersecurity",
        description: "Protect enterprise systems from cyber threats. Learn security tools and practices. Work with global clients on security projects. Growing demand for cybersecurity professionals."
    },
    {
        id: 55,
        title: "Game Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#", "Game Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–16 LPA",
        applyUrl: "https://dream11.com/careers/game-dev",
        description: "Develop fantasy sports gaming platform. Work with Unity and game development tools. India's largest fantasy sports platform. Exciting gaming and sports-tech domain."
    },
    {
        id: 56,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Web3", "JavaScript"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "15–25 LPA",
        applyUrl: "https://polygon.technology/careers/blockchain-dev",
        description: "Build decentralized applications on Polygon network. Work with Solidity and Web3 technologies. Leading Indian blockchain company. Cutting-edge crypto and Web3 space."
    },
    {
        id: 57,
        title: "Product Engineer",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "React", "AWS", "Microservices"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "18–28 LPA",
        applyUrl: "https://atlassian.com/careers/product-engineer",
        description: "Build collaboration tools like Jira and Confluence used by millions. Work with modern tech stack. Global product company with excellent culture. Competitive compensation and benefits."
    },
    {
        id: 58,
        title: "ETL Developer",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["SQL", "Python", "ETL Tools", "Data Warehousing"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–7 LPA",
        applyUrl: "https://mu-sigma.com/careers/etl-developer",
        description: "Build data pipelines and ETL processes for analytics. Work with large datasets and data warehousing. Learn data engineering fundamentals. Analytics and decision sciences company."
    },
    {
        id: 59,
        title: "Solutions Engineer",
        company: "Google Cloud",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["GCP", "Python", "Kubernetes", "Terraform"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "20–30 LPA",
        applyUrl: "https://cloud.google.com/careers/solutions-engineer",
        description: "Help enterprises adopt Google Cloud Platform. Technical pre-sales and solution architecture. Work with cutting-edge cloud technologies. Top-tier compensation and Google perks."
    },
    {
        id: 60,
        title: "Full Stack Engineer",
        company: "Innovaccer",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "PostgreSQL", "AWS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        applyUrl: "https://innovaccer.com/careers/fullstack",
        description: "Build healthcare data platform used by hospitals and clinics. Work with React and Node.js. HealthTech unicorn with social impact. Solve complex healthcare data challenges."
    }
];
